### ISSUE TITLE
Cannot open quickfix list

### ISSUE THREAD

**Issue by ziggystar** [lervag/vimtex#773]
### Error when opening quickfix list

When trying to open the `qf` list, I get the following error instead:

```
Error detected while processing function <SNR>30_fix_paths:
line   23:
E118: Too many arguments for function: setqflist
Error detected while processing function vimtex#qf#toggle:
line    4:
E171: Missing :endif
```

### My history
This happened after an upgrade of vimtex today.

Actually I did a previous update, maybe a week ago, and I didn't have this problem after it. My `git` bisect later shows that I have to go back a month in the revisions for the error to disappear. This is strange and points at the problem being with my configuration, but see later that I tried to use a clean configuration.

Also I installed `lacheck` today simultaneously with upgrading `vimtex`. But the error persists after uninstalling `lacheck` again.

I tried running vim with a clean `vimrc`, see below.

### Steps to reproduce
I opened a minimal file `test.tex`

```tex
\documentclass{minimal}
\begin{document}

Hello World!

\end{document}
```

with minimal `vimrc`

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

" Load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable

" Vimtex options go here
```

by issuing `vim -u vimrc tex.test`. It appears to work, since my other plugins do not show up.

After compiling I try to open the errors with `<leader>le` and I get the error 

```
Error detected while processing function <SNR>30_fix_paths:
line   23:
E118: Too many arguments for function: setqflist
Error detected while processing function vimtex#qf#toggle:
line    4:
E171: Missing :endif
```

The quickfix list doesn't show up.

### Git bisect

I tried to go back some time in the git history, and the error persisted for some time (weeks).
I'm currently at 1e11500253332ec1ed:

 - issues when opening the `qf` list first arise at c46debe, earlier commits work fine
 - at 80ed6a1, the issue appears to be in its final form for me.

**Comment by lervag** [comment]
Which version of Vim are you using?

**Comment by ziggystar** [comment]
Here's the output of `vim --version`:

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
+balloon_eval    +float           +mouse_urxvt     +tcl
+browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         +gettext         -mzscheme        +timers
+cindent         -hangul_input    +netbeans_intg   +title
+clientserver    +iconv           +packages        +toolbar
+clipboard       +insert_expand   +path_extra      +user_commands
+cmdline_compl   +job             +perl            +vertsplit
+cmdline_hist    +jumplist        +persistent_undo +virtualedit
+cmdline_info    +keymap          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  +lua             +rightleft       +writebackup
+diff            +menu            +ruby            +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     +xsmp_interact
+emacs_tags      +mouseshape      +startuptime     +xterm_clipboard
+eval            +mouse_dec       +statusline      -xterm_save
+ex_extra        +mouse_gpm       -sun_workshop    +xpm
+extra_search    -mouse_jsbterm   +syntax          
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.22/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm     

```

**Comment by lervag** [comment]
Whats the output of `:h setqflist(`? That is, for me, I get:

```
setqflist({list} [, {action}[, {what}]])		*setqflist()*
		Create or replace or add to the quickfix list using the items
		in {list}.  Each item in {list} is a dictionary.
		Non-dictionary items in {list} are ignored.  Each dictionary
		item can contain the following entries:
```

The error message you submitted seems to indicate that your `setqflist` only takes two arguments.

**Comment by ziggystar** [comment]
In my version the `{what}` is missing:

```
setqflist({list} [, {action}])                          setqflist()
                Create or replace or add to the quickfix list using the items
                in {list}.  Each item in {list} is a dictionary.
                Non-dictionary items in {list} are ignored.  Each dictionary
                item can contain the following entries:
```

**Comment by lervag** [comment]
Ok, as expected. The problem is due to Vim versions. So, I'll try to figure out which patch added this and add an exception/conditional in the code.

**Comment by ziggystar** [comment]
I can confirm that this fixes the problem.

**Comment by lervag** [comment]
No problem :)

**Comment by urbainvaes** [comment]
Hello,

on Neovim, I get the following error:

```
Error detected while processing function <SNR>119_fix_paths:
line   27:
E731: using Dictionary as a String
Error detected while processing function vimtex#qf#toggle:
line    4:
E171: Missing :endif
```

The result of ":h setqflist" in my case is
```
setqflist({list} [, {action}[, {title}]])		*setqflist()*
		Create or replace or add to the quickfix list using the items
		in {list}.  Each item in {list} is a dictionary.
		Non-dictionary items in {list} are ignored.  Each dictionary
		item can contain the following entries:
```

**Comment by lervag** [comment]
Yes, this is a known issue with neovim. IIRC, it will be fixed in the next release. In the meantime, you can use this in your vimrc to disable the feature that breaks here:

```vim
let g:vimtex_quickfix_latexlog = {'fix_paths' : 0}
```

Note that this disables a function that will try to fix some of the paths in the quickfix list. This is only relevant when you work on multi-file projects, though.
